# Generated by Django 5.2.6 on 2025-09-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField()),
                ('anoPublicacao', models.IntegerField()),
                ('isbn', models.CharField(max_length=20)),
            ],
        ),
    ]
