# Generated by Django 5.2.6 on 2025-09-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.TextField(),
        ),
    ]
