# Generated by Django 5.2.6 on 2025-09-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_livro_autor_alter_livro_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('dataCadastro', models.DateField()),
            ],
        ),
    ]
